In [35]:
import pandas as pd
import numpy as np

In [36]:
# Replace with your Google Sheet URL and modify the link as required
google_sheet_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR3JkRcj5YY4SN7kJzwNyPokTBK_QP_HgV59zsxX6nGEODRVcB6QaX2bJ02ifTm4Q/pub?output=csv'
csv_url = google_sheet_url.replace('/edit?usp=sharing', '/gviz/tq?tqx=out:csv')

main_df = pd.read_csv(csv_url)

main_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,"Wednesday 1 December 2010, 08:26",2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,"Wednesday 1 December 2010, 08:26",2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,"Friday 9 December 2011, 12:50",0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,"Friday 9 December 2011, 12:50",2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,"Friday 9 December 2011, 12:50",4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,"Friday 9 December 2011, 12:50",4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,"Friday 9 December 2011, 12:50",4.95,12680.0,France

In [37]:
main_df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [38]:
# Renaming columns

main_df.columns = ["invoice_id", "stock_id", "product_name", "purchase_quantity","invoice_full_time", "item_price", "customer_id","customer_country"]

c

,invoice_id,stock_id,product_name,purchase_quantity,invoice_full_time,item_price,customer_id,customer_country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,"Wednesday 1 December 2010, 08:26",2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,"Wednesday 1 December 2010, 08:26",2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom

In [49]:
main_df.head(60)

,invoice_id,stock_id,product_name,purchase_quantity,invoice_full_time,item_price,customer_id,customer_country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,"Wednesday 1 December 2010, 08:26",2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,"Wednesday 1 December 2010, 08:26",2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,"Wednesday 1 December 2010, 08:26",3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,"Wednesday 1 December 2010, 08:26",7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,"Wednesday 1 December 2010, 08:26",4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,"Wednesday 1 December 2010, 08:28",1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,"Wednesday 1 December 2010, 08:28",1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,"Wednesday 1 December 2010, 08:34",1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,"Wednesday 1 December 2010, 08:34",2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,"Wednesday 1 December 2010, 08:34",2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,"Wednesday 1 December 2010, 08:34",3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,"Wednesday 1 December 2010, 08:34",1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,"Wednesday 1 December 2010, 08:34",4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,"Wednesday 1 December 2010, 08:34",4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,"Wednesday 1 December 2010, 08:34",9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,"Wednesday 1 December 2010, 08:34",5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,"Wednesday 1 December 2010, 08:34",5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,"Wednesday 1 December 2010, 08:34",7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,"Wednesday 1 December 2010, 08:34",7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,"Wednesday 1 December 2010, 08:34",4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,"Wednesday 1 December 2010, 08:34",4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,"Wednesday 1 December 2010, 08:34",4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,"Wednesday 1 December 2010, 08:34",4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,"Wednesday 1 December 2010, 08:35",5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,"Wednesday 1 December 2010, 08:45",3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,"Wednesday 1 December 2010, 08:45",3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,"Wednesday 1 December 2010, 08:45",3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,"Wednesday 1 December 2010, 08:45",0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,"Wednesday 1 December 2010, 08:45",0.65,12583.0,France
31,536370,10002,INFLATABLE POLITICAL GLOBE,48,"Wednesday 1 December 2010, 08:45",0.85,12583.0,France
32,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,"Wednesday 1 December 2010, 08:45",1.25,12583.0,France
33,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,"Wednesday 1 December 2010, 08:45",2.95,12583.0,France
34,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,"Wednesday 1 December 2010, 08:45",2.95,12583.0,France
35,536370,22629,SPACEBOY LUNCH BOX,24,"Wednesday 1 December 2010, 08:45",1.95,12583.0,France
36,536370,22659,LUNCH BOX I LOVE LONDON,24,"Wednesday 1 December 2010, 08:45",1.95,12583.0,France
37,536370,22631,CIRCUS PARADE LUNCH BOX,24,"Wednesday 1 December 2010, 08:45",1.95,12583.0,France
38,536370,22661,CHARLOTTE BAG DOLLY GIRL DESIGN,20,"Wednesday 1 December 2010, 08:45",0.85,12583.0,France
39,536370,21731,RED TOADSTOOL LED NIGHT LIGHT,24,"Wednesday 1 December 2010, 08:45",1.65,12583.0,France
40,536370,22900,SET 2 TEA TOWELS I LOVE LONDON,24,"Wednesday 1 December 2010, 08:45",2.95,12583.0,France
41,536370,21913,VINTAGE SEASIDE JIGSAW PUZZLES,12,"Wednesday 1 December 2010, 08:45",3.75,12583.0,France
42,536370,22540,MINI JIGSAW CIRCUS PARADE,24,"Wednesday 1 December 2010, 08:45",0.42,12583.0,France
43,536370,22544,MINI JIGSAW SPACEBOY,24,"Wednesday 1 December 2010, 08:45",0.42,12583.0,France
44,536370,22492,MINI PAINT SET VINTAGE,36,"Wednesday 1 December 2010, 08:45",0.65,12583.0,France
45,536370,POST,POSTAGE,3,"Wednesday 1 December 2010, 08:45",18.00,12583.0,France
46,536371,22086,PAPER CHAIN KIT 50'S CHRISTMAS,80,"Wednesday 1 December 2010, 09:00",2.55,13748.0,United Kingdom
47,536372,22632,HAND WARMER RED POLKA DOT,6,"Wednesday 1 December 2010, 09:01",1.85,17850.0,United Kingdom
48,536372,22633,HAND WARMER UNION JACK,6,"Wednesday 1 December 2010, 09:01",1.85,17850.0,United Kingdom
49,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,"Wednesday 1 December 2010, 09:02",2.55,17850.0,United Kingdom
50,536373,71053,WHITE METAL LANTERN,6,"Wednesday 1 December 2010, 09:02",3.39,17850.0,United Kingdom
51,536373,84406B,CREAM CUPID HEARTS COAT HANGER,8,"Wednesday 1 December 2010, 09:02",2.75,17850.0,United Kingdom
52,536373,20679,EDWARDIAN PARASOL RED,6,"Wednesday 1 December 2010, 09:02",4.95,17850.0,United Kingdom
53,536373,37370,RETRO COFFEE MUGS ASSORTED,6,"Wednesday 1 December 2010, 09:02",1.06,17850.0,United Kingdom
54,536373,21871,SAVE THE PLANET MUG,6,"Wednesday 1 December 2010, 09:02",1.06,17850.0,United Kingdom
55,536373,21071,VINTAGE BILLBOARD DRINK ME MUG,6,"Wednesday 1 December 2010, 09:02",1.06,17850.0,United Kingdom
56,536373,21068,VINTAGE BILLBOARD LOVE/HATE MUG,6,"Wednesday 1 December 2010, 09:02",1.06,17850.0,United Kingdom
57,536373,82483,WOOD 2 DRAWER CABINET WHITE FINISH,2,"Wednesday 1 December 2010, 09:02",4.95,17850.0,United Kingdom
58,536373,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,"Wednesday 1 December 2010, 09:02",6.95,17850.0,United Kingdom
59,536373,82482,WOODEN PICTURE FRAME WHITE FINISH,6,"Wednesday 1 December 2010, 09:02",2.10,17850.0,United Kingdom

In [50]:
main_df.tail(5)

,invoice_id,stock_id,product_name,purchase_quantity,invoice_full_time,item_price,customer_id,customer_country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,"Friday 9 December 2011, 12:50",0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,"Friday 9 December 2011, 12:50",2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,"Friday 9 December 2011, 12:50",4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,"Friday 9 December 2011, 12:50",4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,"Friday 9 December 2011, 12:50",4.95,12680.0,France

In [47]:
## Rami suggested creating categories
## Look into ARIMA and Prophet models

main_df["product_name"].nunique()

4223

In [39]:
main_df["customer_country"].value_counts()

customer_country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [40]:
### Taking care of special cases in customer_country column

In [41]:
# Custom taking care of special cases
def convert_countries(row):
    if row == "Unspecified" or row == "European Community":
        return np.nan
    elif row == "EIRE":
        return "Ireland"
    elif row == "RSA":
        return "South Africa"
    else:
        return row

# Apply custom function to each element in DataFrame column 'A'
main_df['customer_country'] = main_df['customer_country'].apply(convert_countries)

In [42]:
main_df["customer_country"].value_counts()

customer_country
United Kingdom          495478
Germany                   9495
France                    8557
Ireland                   8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
South Africa                58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [46]:
main_df.shape

(541909, 8)

In [43]:
### Creating customer_region
# UK
# Europe
# Americas
# Asia
# Africa

# UK
uk = ["United Kingdom", "Channel Islands"]

# Europe
europe = [
    "Germany", "France", "Ireland", "Spain", "Netherlands", "Belgium",
    "Switzerland", "Portugal", "Norway", "Italy", "Finland", "Cyprus",
    "Sweden", "Austria", "Denmark", "Poland", "Iceland", "Greece",
    "Malta", "Lithuania", "Czech Republic"]

# Americas
americas = ["USA", "Canada", "Brazil"]

# Asia
asia = [
    "Japan", "Israel", "Hong Kong", "Singapore", "United Arab Emirates",
    "Lebanon", "Bahrain", "Saudi Arabia"
]

# Africa
africa = ["South Africa"]

In [ ]:
## Handle NA values